version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sample
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3966:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8880:8080

  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - 3211:8080
    volumes:
      - ./docs:/docs
    environment:
      SWAGGER_JSON: /docs/open-api.json
